version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing Serverless...
      - npm install -g serverless
  pre_build:
    commands:
      - echo Install source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Deployment started on `date`
      - echo Deploying with the Serverless Framework
      - echo Deploying with the Serverless Framework ENV_NAME :$ENV_NAME
      #- SLS_DEBUG=* sls remove
      - SLS_DEBUG=* sls deploy -v -s $ENV_NAME
  post_build:
    commands:
      - echo Deployment completed on `date`